m1 = raw_input("Enter the marks of student 1\n")
m2 = raw_input("Enter the marks of student 2\n")
m3 = raw_input("Enter the marks of student 3\n")
m4 = raw_input("Enter the marks of student 4\n")
m5 = raw_input("Enter the marks of student 5\n")
m6 = raw_input("Enter the marks of student 6\n")
m1=int(m1)
m2=int(m2)
m3=int(m3)
m4=int(m4)
m5=int(m5)
m6=int(m6)
studentMarks = [m1, m2, m3, m4, m5, m6]
studentMarks.sort()
print(studentMarks)
