myDict={}
name1 = raw_input("Enter the name of student 1 :")
lang1 = raw_input("Enter the favourite language of student 1 : ")
myDict.update({name1 : lang1})
name2 = raw_input("Enter the name of student 2 :")
lang2 = raw_input("Enter the favourite language of student 2 : ")
myDict.update({name2 : lang2})
name3 = raw_input("Enter the name of student 3 :")
lang3 = raw_input("Enter the favourite language of student 3 : ")
myDict.update({name3 : lang3})
name4 = raw_input("Enter the name of student 4 :")
lang4 = raw_input("Enter the favourite language of student 4 : ")
myDict.update({name4 : lang4})
print(myDict.items())