num1 = int(raw_input("Enter the number 1"))
num2 = int(raw_input("Enter the number 2"))
num3 = int(raw_input("Enter the number 3"))
num4 = int(raw_input("Enter the number 4"))
num5 = int(raw_input("Enter the number 5"))
num6 = int(raw_input("Enter the number 6"))
num7 = int(raw_input("Enter the number 7"))
num8 = int(raw_input("Enter the number 8"))
# num1 = int(num1)
# num2 = int(num2)
# num3 = int(num3)
# num4 = int(num4)
# num5 = int(num5)
# num6 = int(num6)
# num7 = int(num7)
# num8 = int(num8)
allNums = {num1, num2, num3, num4, num5, num6, num7, num8}
print(allNums)
